### ISSUE TITLE
`grow` causes UB with array as storage

### ISSUE THREAD

**Issue by Stupremee** [RustyYato/generic-vec#4]
```rust
use generic_vec::GenericVec;

fn main() {
    let mut buf: GenericVec<u8, [u8; 1]> = GenericVec::with_capacity(1);
    buf.grow(1, 0u8);
}
```

This code will panic with the message 
```
Tried to `push_unchecked` past capacity! This is UB in release mode
```
and will cause UB in release mode.

The exact code is used by the `gvec` macro, so you can achieve the same behaviour using the `gvec` macro

**Comment by RustyYato** [comment]
Thanks! It turns out there was an off by one error within my implementation of `grow`, which is now fixed.
