### ISSUE TITLE
GenericVec::extend_from_slice runs past storage

### ISSUE THREAD

**Issue by tilpner** [RustyYato/generic-vec#6]
With a GenericVec of size 0, extend_from_slice reserves another 0 elements, then tries to extend unchecked, and runs off into memory it has no business touching.

From the doc comment of reserve, it seems like

https://github.com/RustyYato/generic-vec/blob/c7aeeb58273f3a76ec0bde26fb5e25177d0feedb/src/lib.rs#L1876

should instead be

```rust
self.reserve(slice.len());
```

**Comment by RustyYato** [comment]
Oof, nice catch
